# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jose/NetBeansProjects/QtApplication_1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jose/NetBeansProjects/QtApplication_1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jose/NetBeansProjects/QtApplication_1/CMakeFiles /home/jose/NetBeansProjects/QtApplication_1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jose/NetBeansProjects/QtApplication_1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GuettaGrabber

# Build rule for target.
GuettaGrabber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GuettaGrabber
.PHONY : GuettaGrabber

# fast build rule for target.
GuettaGrabber/fast:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/build
.PHONY : GuettaGrabber/fast

GLWidget.o: GLWidget.cpp.o
.PHONY : GLWidget.o

# target to build an object file
GLWidget.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GLWidget.cpp.o
.PHONY : GLWidget.cpp.o

GLWidget.i: GLWidget.cpp.i
.PHONY : GLWidget.i

# target to preprocess a source file
GLWidget.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GLWidget.cpp.i
.PHONY : GLWidget.cpp.i

GLWidget.s: GLWidget.cpp.s
.PHONY : GLWidget.s

# target to generate assembly for a file
GLWidget.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GLWidget.cpp.s
.PHONY : GLWidget.cpp.s

Guetta.o: Guetta.cpp.o
.PHONY : Guetta.o

# target to build an object file
Guetta.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Guetta.cpp.o
.PHONY : Guetta.cpp.o

Guetta.i: Guetta.cpp.i
.PHONY : Guetta.i

# target to preprocess a source file
Guetta.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Guetta.cpp.i
.PHONY : Guetta.cpp.i

Guetta.s: Guetta.cpp.s
.PHONY : Guetta.s

# target to generate assembly for a file
Guetta.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Guetta.cpp.s
.PHONY : Guetta.cpp.s

GuettaCloud.o: GuettaCloud.cpp.o
.PHONY : GuettaCloud.o

# target to build an object file
GuettaCloud.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaCloud.cpp.o
.PHONY : GuettaCloud.cpp.o

GuettaCloud.i: GuettaCloud.cpp.i
.PHONY : GuettaCloud.i

# target to preprocess a source file
GuettaCloud.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaCloud.cpp.i
.PHONY : GuettaCloud.cpp.i

GuettaCloud.s: GuettaCloud.cpp.s
.PHONY : GuettaCloud.s

# target to generate assembly for a file
GuettaCloud.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaCloud.cpp.s
.PHONY : GuettaCloud.cpp.s

GuettaFeatures.o: GuettaFeatures.cpp.o
.PHONY : GuettaFeatures.o

# target to build an object file
GuettaFeatures.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaFeatures.cpp.o
.PHONY : GuettaFeatures.cpp.o

GuettaFeatures.i: GuettaFeatures.cpp.i
.PHONY : GuettaFeatures.i

# target to preprocess a source file
GuettaFeatures.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaFeatures.cpp.i
.PHONY : GuettaFeatures.cpp.i

GuettaFeatures.s: GuettaFeatures.cpp.s
.PHONY : GuettaFeatures.s

# target to generate assembly for a file
GuettaFeatures.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaFeatures.cpp.s
.PHONY : GuettaFeatures.cpp.s

GuettaICP.o: GuettaICP.cpp.o
.PHONY : GuettaICP.o

# target to build an object file
GuettaICP.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaICP.cpp.o
.PHONY : GuettaICP.cpp.o

GuettaICP.i: GuettaICP.cpp.i
.PHONY : GuettaICP.i

# target to preprocess a source file
GuettaICP.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaICP.cpp.i
.PHONY : GuettaICP.cpp.i

GuettaICP.s: GuettaICP.cpp.s
.PHONY : GuettaICP.s

# target to generate assembly for a file
GuettaICP.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaICP.cpp.s
.PHONY : GuettaICP.cpp.s

GuettaTime.o: GuettaTime.cpp.o
.PHONY : GuettaTime.o

# target to build an object file
GuettaTime.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaTime.cpp.o
.PHONY : GuettaTime.cpp.o

GuettaTime.i: GuettaTime.cpp.i
.PHONY : GuettaTime.i

# target to preprocess a source file
GuettaTime.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaTime.cpp.i
.PHONY : GuettaTime.cpp.i

GuettaTime.s: GuettaTime.cpp.s
.PHONY : GuettaTime.s

# target to generate assembly for a file
GuettaTime.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaTime.cpp.s
.PHONY : GuettaTime.cpp.s

GuettaViewer.o: GuettaViewer.cpp.o
.PHONY : GuettaViewer.o

# target to build an object file
GuettaViewer.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaViewer.cpp.o
.PHONY : GuettaViewer.cpp.o

GuettaViewer.i: GuettaViewer.cpp.i
.PHONY : GuettaViewer.i

# target to preprocess a source file
GuettaViewer.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaViewer.cpp.i
.PHONY : GuettaViewer.cpp.i

GuettaViewer.s: GuettaViewer.cpp.s
.PHONY : GuettaViewer.s

# target to generate assembly for a file
GuettaViewer.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/GuettaViewer.cpp.s
.PHONY : GuettaViewer.cpp.s

Ramsac.o: Ramsac.cpp.o
.PHONY : Ramsac.o

# target to build an object file
Ramsac.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Ramsac.cpp.o
.PHONY : Ramsac.cpp.o

Ramsac.i: Ramsac.cpp.i
.PHONY : Ramsac.i

# target to preprocess a source file
Ramsac.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Ramsac.cpp.i
.PHONY : Ramsac.cpp.i

Ramsac.s: Ramsac.cpp.s
.PHONY : Ramsac.s

# target to generate assembly for a file
Ramsac.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Ramsac.cpp.s
.PHONY : Ramsac.cpp.s

SiftGPUFeatureDetector.o: SiftGPUFeatureDetector.cpp.o
.PHONY : SiftGPUFeatureDetector.o

# target to build an object file
SiftGPUFeatureDetector.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/SiftGPUFeatureDetector.cpp.o
.PHONY : SiftGPUFeatureDetector.cpp.o

SiftGPUFeatureDetector.i: SiftGPUFeatureDetector.cpp.i
.PHONY : SiftGPUFeatureDetector.i

# target to preprocess a source file
SiftGPUFeatureDetector.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/SiftGPUFeatureDetector.cpp.i
.PHONY : SiftGPUFeatureDetector.cpp.i

SiftGPUFeatureDetector.s: SiftGPUFeatureDetector.cpp.s
.PHONY : SiftGPUFeatureDetector.s

# target to generate assembly for a file
SiftGPUFeatureDetector.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/SiftGPUFeatureDetector.cpp.s
.PHONY : SiftGPUFeatureDetector.cpp.s

StandardCamera.o: StandardCamera.cpp.o
.PHONY : StandardCamera.o

# target to build an object file
StandardCamera.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/StandardCamera.cpp.o
.PHONY : StandardCamera.cpp.o

StandardCamera.i: StandardCamera.cpp.i
.PHONY : StandardCamera.i

# target to preprocess a source file
StandardCamera.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/StandardCamera.cpp.i
.PHONY : StandardCamera.cpp.i

StandardCamera.s: StandardCamera.cpp.s
.PHONY : StandardCamera.s

# target to generate assembly for a file
StandardCamera.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/StandardCamera.cpp.s
.PHONY : StandardCamera.cpp.s

Viewer.o: Viewer.cpp.o
.PHONY : Viewer.o

# target to build an object file
Viewer.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Viewer.cpp.o
.PHONY : Viewer.cpp.o

Viewer.i: Viewer.cpp.i
.PHONY : Viewer.i

# target to preprocess a source file
Viewer.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Viewer.cpp.i
.PHONY : Viewer.cpp.i

Viewer.s: Viewer.cpp.s
.PHONY : Viewer.s

# target to generate assembly for a file
Viewer.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/Viewer.cpp.s
.PHONY : Viewer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/main.cpp.s
.PHONY : main.cpp.s

moc_GLWidget.o: moc_GLWidget.cxx.o
.PHONY : moc_GLWidget.o

# target to build an object file
moc_GLWidget.cxx.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GLWidget.cxx.o
.PHONY : moc_GLWidget.cxx.o

moc_GLWidget.i: moc_GLWidget.cxx.i
.PHONY : moc_GLWidget.i

# target to preprocess a source file
moc_GLWidget.cxx.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GLWidget.cxx.i
.PHONY : moc_GLWidget.cxx.i

moc_GLWidget.s: moc_GLWidget.cxx.s
.PHONY : moc_GLWidget.s

# target to generate assembly for a file
moc_GLWidget.cxx.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GLWidget.cxx.s
.PHONY : moc_GLWidget.cxx.s

moc_Guetta.o: moc_Guetta.cxx.o
.PHONY : moc_Guetta.o

# target to build an object file
moc_Guetta.cxx.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Guetta.cxx.o
.PHONY : moc_Guetta.cxx.o

moc_Guetta.i: moc_Guetta.cxx.i
.PHONY : moc_Guetta.i

# target to preprocess a source file
moc_Guetta.cxx.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Guetta.cxx.i
.PHONY : moc_Guetta.cxx.i

moc_Guetta.s: moc_Guetta.cxx.s
.PHONY : moc_Guetta.s

# target to generate assembly for a file
moc_Guetta.cxx.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Guetta.cxx.s
.PHONY : moc_Guetta.cxx.s

moc_GuettaViewer.o: moc_GuettaViewer.cxx.o
.PHONY : moc_GuettaViewer.o

# target to build an object file
moc_GuettaViewer.cxx.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GuettaViewer.cxx.o
.PHONY : moc_GuettaViewer.cxx.o

moc_GuettaViewer.i: moc_GuettaViewer.cxx.i
.PHONY : moc_GuettaViewer.i

# target to preprocess a source file
moc_GuettaViewer.cxx.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GuettaViewer.cxx.i
.PHONY : moc_GuettaViewer.cxx.i

moc_GuettaViewer.s: moc_GuettaViewer.cxx.s
.PHONY : moc_GuettaViewer.s

# target to generate assembly for a file
moc_GuettaViewer.cxx.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_GuettaViewer.cxx.s
.PHONY : moc_GuettaViewer.cxx.s

moc_Viewer.o: moc_Viewer.cxx.o
.PHONY : moc_Viewer.o

# target to build an object file
moc_Viewer.cxx.o:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Viewer.cxx.o
.PHONY : moc_Viewer.cxx.o

moc_Viewer.i: moc_Viewer.cxx.i
.PHONY : moc_Viewer.i

# target to preprocess a source file
moc_Viewer.cxx.i:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Viewer.cxx.i
.PHONY : moc_Viewer.cxx.i

moc_Viewer.s: moc_Viewer.cxx.s
.PHONY : moc_Viewer.s

# target to generate assembly for a file
moc_Viewer.cxx.s:
	$(MAKE) -f CMakeFiles/GuettaGrabber.dir/build.make CMakeFiles/GuettaGrabber.dir/moc_Viewer.cxx.s
.PHONY : moc_Viewer.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GuettaGrabber"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GLWidget.o"
	@echo "... GLWidget.i"
	@echo "... GLWidget.s"
	@echo "... Guetta.o"
	@echo "... Guetta.i"
	@echo "... Guetta.s"
	@echo "... GuettaCloud.o"
	@echo "... GuettaCloud.i"
	@echo "... GuettaCloud.s"
	@echo "... GuettaFeatures.o"
	@echo "... GuettaFeatures.i"
	@echo "... GuettaFeatures.s"
	@echo "... GuettaICP.o"
	@echo "... GuettaICP.i"
	@echo "... GuettaICP.s"
	@echo "... GuettaTime.o"
	@echo "... GuettaTime.i"
	@echo "... GuettaTime.s"
	@echo "... GuettaViewer.o"
	@echo "... GuettaViewer.i"
	@echo "... GuettaViewer.s"
	@echo "... Ramsac.o"
	@echo "... Ramsac.i"
	@echo "... Ramsac.s"
	@echo "... SiftGPUFeatureDetector.o"
	@echo "... SiftGPUFeatureDetector.i"
	@echo "... SiftGPUFeatureDetector.s"
	@echo "... StandardCamera.o"
	@echo "... StandardCamera.i"
	@echo "... StandardCamera.s"
	@echo "... Viewer.o"
	@echo "... Viewer.i"
	@echo "... Viewer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_GLWidget.o"
	@echo "... moc_GLWidget.i"
	@echo "... moc_GLWidget.s"
	@echo "... moc_Guetta.o"
	@echo "... moc_Guetta.i"
	@echo "... moc_Guetta.s"
	@echo "... moc_GuettaViewer.o"
	@echo "... moc_GuettaViewer.i"
	@echo "... moc_GuettaViewer.s"
	@echo "... moc_Viewer.o"
	@echo "... moc_Viewer.i"
	@echo "... moc_Viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

